# Generated by Django 6.1 on 2026-08-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especialidade', models.CharField(max_length=255)),
                ('registro_conselho', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('vagas_totais_dia', models.PositiveIntegerField(help_text='Quantidade de vagas disponíveis por dia')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='scheduling.especialista')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado')], default='disponivel', max_length=20)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='scheduling.agenda')),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='scheduling.especialista')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('horario_atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='scheduling.horarioatendimento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='horarioatendimento',
            constraint=models.UniqueConstraint(fields=('especialista', 'data', 'horario'), name='unique_horario_especialista'),
        ),
    ]
