# Generated by Django 6.1 on 2026-08-25 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cliente_email',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='cliente_nome',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
